# Generated by Django 4.2.17 on 2026-05-01 05:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('fuqaro', 'Fuqaro'), ('hokimiyat', 'Hokimiyat xodimi')], default='fuqaro', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_authority_approved', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('waste_type', models.CharField(choices=[('uy', 'Uy chiqindisi'), ('qurilish', 'Qurilish chiqindisi'), ('plastik', 'Plastmassa/Plastik'), ('xavfli', 'Xavfli chiqindilar'), ('boshqa', 'Boshqa')], max_length=20, verbose_name='Chiqindi turi')),
                ('size', models.CharField(choices=[('kichik', 'Kichik'), ('orta', "O'rta"), ('katta', 'Katta')], max_length=10, verbose_name='Hajmi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('qabul_qilindi', 'Qabul qilindi'), ('jarayonda', "Ko'rib chiqilmoqda"), ('tozalanmoqda', 'Tozalanmoqda'), ('tozalandi', 'Tozalandi')], default='kutilmoqda', max_length=20, verbose_name='Holati')),
                ('viloyat', models.CharField(blank=True, choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('andijon', 'Andijon viloyati'), ('fargona', "Farg'ona viloyati"), ('namangan', 'Namangan viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('xorazm', 'Xorazm viloyati'), ('jizzax', 'Jizzax viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=50, verbose_name='Viloyat')),
                ('tuman', models.CharField(blank=True, max_length=100, verbose_name='Tuman')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('authority_note', models.TextField(blank=True, verbose_name='Hokimiyat izohi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Fuqaro')),
            ],
            options={
                'verbose_name': 'Chiqindi xabari',
                'verbose_name_plural': 'Chiqindi xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('yangi_xabar', 'Yangi xabar'), ('holat_ozgardi', "Holat o'zgardi"), ('tayinlandi', 'Tayinlandi')], max_length=30, verbose_name='Turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chiqindi_app.wastereport', verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
